### ISSUE TITLE
Error modules_v4/huhwt/InteractiveTreeXT.php: 56

### ISSUE THREAD

**Issue by yako1984** [huhwt/huhwt-xtv#6]
Error not loading webtrees‑2.0.16 version - modules_v4/huhwt/InteractiveTreeXT.php: 56

**Comment by huhwt** [comment]
Hallo, what error messages do you get?

**Comment by yako1984** [comment]
I paste the module in the folder and the web does not load me.

![Screenshot_1](https://user-images.githubusercontent.com/67491705/126053521-2cf1eaee-a6c6-4449-96c1-32cb2fcdbdfd.jpg)

**Comment by huhwt** [comment]
Well, the problem is - you loaded the wrong files. The Github-Repo is for development purposes. For to use the module in an webtrees environment, please tetch the zip from the last release-repo (huhwt-xtv-1.07.zip), expand it und use this directory. Its name is huhwt-xtv. It should work fine for you ...
